# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, dataDefault, dataTimeout, deepseq, exceptions, filepath
, ghcPaths, liquidFixpoint, liquidhaskell, mtl, syb, tagged, tasty
, tastyHunit, text, textFormat, transformers, unorderedContainers
, vector
}:

cabal.mkDerivation (self: {
  pname = "target";
  version = "0.1.0.0";
  src = (import <nixpkgs> {}).haskellFilterSource ["bench" "examples" "test"] ./.;
  doCheck = false;
  buildDepends = [
    dataDefault dataTimeout exceptions filepath ghcPaths liquidFixpoint
    liquidhaskell mtl syb tagged text textFormat transformers
    unorderedContainers vector
  ];
  testDepends = [
    deepseq liquidFixpoint liquidhaskell mtl tagged tasty tastyHunit
    unorderedContainers
  ];
  meta = {
    description = "Generate test-suites from types";
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
